# Importing tensorflow libraries


In [ ]:
import tensorflow as tf
print(tf.__version__)

2.14.0


#Creating tensors using `tf.constant()`
* scalar
* vector
* matrix
* tensor

In [ ]:
scalar = tf.constant(5,dtype=(tf.float32))
print("scalar information:",scalar)
print("scalar shape:",scalar.shape)
print("scalar data type:",scalar.dtype)
print("scalar valaue:",scalar.numpy())
print("scalar dimension:",scalar.ndim)

scalar information: tf.Tensor(5.0, shape=(), dtype=float32)
scalar shape: ()
scalar data type: <dtype: 'float32'>
scalar valaue: 5.0
scalar dimension: 0


In [ ]:
vector = tf.constant([4,5],dtype=(tf.float16))
print("vector information:",vector)
print("vector shape:",vector.shape)
print("vector data type:",vector.dtype)
print("vector value:",vector.numpy())
print("vector dimension",vector.ndim)

vector information: tf.Tensor([4. 5.], shape=(2,), dtype=float16)
vector shape: (2,)
vector data type: <dtype: 'float16'>
vector value: [4. 5.]
vector dimension 1


In [ ]:
matrix = tf.constant([[2,4],
                      [5,8],
                      [1,7]],dtype=(tf.float32))
print("matrix information:\n",matrix)
print("matrix shape:",matrix.shape)
print("matrix data type:",matrix.dtype)
print("matrix value:\n",matrix.numpy())
print("matrix dimension:", matrix.ndim)

matrix information:
 tf.Tensor(
[[2. 4.]
 [5. 8.]
 [1. 7.]], shape=(3, 2), dtype=float32)
matrix shape: (3, 2)
matrix data type: <dtype: 'float32'>
matrix value:
 [[2. 4.]
 [5. 8.]
 [1. 7.]]
matrix dimension: 2


In [ ]:
tensor = tf.constant([[[3,4,6],[7,5,8],[2,4,6]],
                      [[7,3,6],[2,8,2],[5,8,9]]],dtype=tf.float32)
print("tensor information:",tensor)
print("tensor shape:",tensor.shape)
print("tensor data type:",tensor.dtype)
print("tensor value:\n",tensor.numpy())
print("tensor dimension:",tensor.ndim)

tensor information: tf.Tensor(
[[[3. 4. 6.]
  [7. 5. 8.]
  [2. 4. 6.]]

 [[7. 3. 6.]
  [2. 8. 2.]
  [5. 8. 9.]]], shape=(2, 3, 3), dtype=float32)
tensor shape: (2, 3, 3)
tensor data type: <dtype: 'float32'>
tensor value:
 [[[3. 4. 6.]
  [7. 5. 8.]
  [2. 4. 6.]]

 [[7. 3. 6.]
  [2. 8. 2.]
  [5. 8. 9.]]]
tensor dimension: 3


# Creating tensors using `tf.Variable`

In [ ]:
var = tf.Variable([[5,6,7],[2,5,6]],dtype=tf.float32)
var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[5., 6., 7.],
       [2., 5., 6.]], dtype=float32)>

In [ ]:
var.assign([[1,2,3],
            [4,5,6]])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

# Creating tensors using `tf.random`
* using `.uniform`
* using `.normal`

In [ ]:
random_uniform = tf.random.uniform([2,2,3],dtype=tf.int32,minval=0,maxval=5,seed=10)
random_uniform,random_uniform.ndim

(<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[0, 0, 0],
         [3, 4, 2]],
 
        [[2, 1, 0],
         [2, 1, 0]]], dtype=int32)>,
 3)

In [ ]:
random_normal = tf.random.normal([2,3,3],dtype=tf.float16)
random_normal

<tf.Tensor: shape=(2, 3, 3), dtype=float16, numpy=
array([[[-0.1565, -2.219 , -0.69  ],
        [ 0.8228,  0.8687,  0.6646],
        [-0.71  ,  0.8296,  2.043 ]],

       [[ 1.328 ,  0.6206, -0.3652],
        [-2.363 ,  1.053 ,  0.807 ],
        [ 0.436 ,  1.265 ,  0.562 ]]], dtype=float16)>

In [ ]:
tf.random.set_seed(42)
random_fix_uniform = tf.random.uniform([2,3,3],dtype=tf.float16,seed=10)
random_fix_uniform

<tf.Tensor: shape=(2, 3, 3), dtype=float16, numpy=
array([[[0.7744 , 0.1797 , 0.4492 ],
        [0.748  , 0.1514 , 0.8174 ],
        [0.04883, 0.3828 , 0.4502 ]],

       [[0.3018 , 0.661  , 0.5967 ],
        [0.8477 , 0.0957 , 0.707  ],
        [0.2285 , 0.08105, 0.1953 ]]], dtype=float16)>

In [ ]:
tf.random.set_seed(42)
rand_fix_normal = tf.random.normal([2,3,3],dtype=tf.float16)
rand_fix_normal

<tf.Tensor: shape=(2, 3, 3), dtype=float16, numpy=
array([[[ 0.3274, -0.843 ,  0.3193],
        [-1.407 , -2.389 , -1.039 ],
        [-0.557 ,  0.5396,  1.699 ]],

       [[ 0.2888, -1.507 , -0.2646],
        [-0.597 , -1.917 , -0.6206],
        [ 0.8506, -0.406 , -3.025 ]]], dtype=float16)>

# Shuffle a tensor using `tf.random.shuffle`

In [ ]:
tf.random.set_seed(42)
x = tf.random.uniform([3,3],dtype=tf.int32,minval=0,maxval=50)
y = tf.random.uniform([2,3],dtype=tf.int32,minval=0,maxval=50)
x,y

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[37, 39, 11],
        [36, 42, 34],
        [33, 43, 21]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[48, 43, 19],
        [44, 32, 13]], dtype=int32)>)

In [ ]:
x_shuffle = tf.random.shuffle(x)
y_shuffle = tf.random.shuffle(y)
x_shuffle ,y_shuffle

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[37, 39, 11],
        [33, 43, 21],
        [36, 42, 34]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[44, 32, 13],
        [48, 43, 19]], dtype=int32)>)

# Reshape a tensor using `tf.reshape`

In [ ]:
tf.shape(x),tf.shape(y)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>)

In [ ]:
x_reshape = tf.reshape(x,[3,3])
y_reshape = tf.reshape(y,[3,2])
x, x_reshape, y, y_reshape

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[37, 39, 11],
        [36, 42, 34],
        [33, 43, 21]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[37, 39, 11],
        [36, 42, 34],
        [33, 43, 21]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[48, 43, 19],
        [44, 32, 13]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[48, 43],
        [19, 44],
        [32, 13]], dtype=int32)>)

# Transpose a tensor using `tf.transpose`

In [ ]:
x_transpose = tf.transpose(x)
y_transpose = tf.transpose(y)
x, x_transpose, y, y_transpose

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[37, 39, 11],
        [36, 42, 34],
        [33, 43, 21]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[37, 36, 33],
        [39, 42, 43],
        [11, 34, 21]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[48, 43, 19],
        [44, 32, 13]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[48, 44],
        [43, 32],
        [19, 13]], dtype=int32)>)

# Filling zero/one elements in tensors using `tf.zero()`

In [ ]:
zero = tf.zeros([2,3,3],dtype=tf.int32)
one = tf.ones([3,3,3])
zero, one

(<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
 array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
 array([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],
 
        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],
 
        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]], dtype=float32)>)

# Executing arithmetic operations in tensorflow using:
* `+` or `tf.add` or `tf.math.add`
* `-` or `tf.subtract` or `tf.math.subtract`
* `*` or `tf.multiply` or `tf.math.multiply`
* `/` or `tf.divide` or `tf.math.divide`

In [ ]:
x,y

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[37, 39, 11],
        [36, 42, 34],
        [33, 43, 21]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[48, 43, 19],
        [44, 32, 13]], dtype=int32)>)

In [ ]:
print(x)
print(x+10)
print(tf.add(x,10))
print(tf.math.add(x,10))

tf.Tensor(
[[37 39 11]
 [36 42 34]
 [33 43 21]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[47 49 21]
 [46 52 44]
 [43 53 31]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[47 49 21]
 [46 52 44]
 [43 53 31]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[47 49 21]
 [46 52 44]
 [43 53 31]], shape=(3, 3), dtype=int32)


In [ ]:
print(x)
print(x-10)
print(tf.subtract(x,10))
print(tf.math.subtract(x,10))

tf.Tensor(
[[37 39 11]
 [36 42 34]
 [33 43 21]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[27 29  1]
 [26 32 24]
 [23 33 11]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[27 29  1]
 [26 32 24]
 [23 33 11]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[27 29  1]
 [26 32 24]
 [23 33 11]], shape=(3, 3), dtype=int32)


In [ ]:
print(x)
print(x*10)
print(tf.multiply(x,10))
print(tf.math.multiply(x,10))

tf.Tensor(
[[37 39 11]
 [36 42 34]
 [33 43 21]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[370 390 110]
 [360 420 340]
 [330 430 210]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[370 390 110]
 [360 420 340]
 [330 430 210]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[370 390 110]
 [360 420 340]
 [330 430 210]], shape=(3, 3), dtype=int32)


In [ ]:
print(x)
print(x/10)
print(tf.divide(x,10))
print(tf.math.divide(x,10))

tf.Tensor(
[[37 39 11]
 [36 42 34]
 [33 43 21]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[3.7 3.9 1.1]
 [3.6 4.2 3.4]
 [3.3 4.3 2.1]], shape=(3, 3), dtype=float64)
tf.Tensor(
[[3.7 3.9 1.1]
 [3.6 4.2 3.4]
 [3.3 4.3 2.1]], shape=(3, 3), dtype=float64)
tf.Tensor(
[[3.7 3.9 1.1]
 [3.6 4.2 3.4]
 [3.3 4.3 2.1]], shape=(3, 3), dtype=float64)


# Multiplication of tensors using:
* `tf.reshape` and `tf.transpose`
  1. `*`
  2. `tf.matmul`
  3. `@`
  4. `tf.tensordot`

In [ ]:
tf.random.set_seed(42)
w = tf.random.uniform([3,3],dtype=tf.int32, minval=0,maxval=100,seed=10)
x, y, x_reshape, y_reshape, x_transpose, y_transpose

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[37, 39, 11],
        [36, 42, 34],
        [33, 43, 21]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[48, 43, 19],
        [44, 32, 13]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[37, 39, 11],
        [36, 42, 34],
        [33, 43, 21]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[48, 43],
        [19, 44],
        [32, 13]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[37, 36, 33],
        [39, 42, 43],
        [11, 34, 21]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[48, 44],
        [43, 32],
        [19, 13]], dtype=int32)>)

In [ ]:
print(x*w)
print(tf.matmul(x,w))
print(x@w)
print(tf.tensordot(x,w,1))

tf.Tensor(
[[2109 2652  528]
 [3240 1470 3026]
 [1122 1548  525]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[5993 4277 5522]
 [6988 5142 6316]
 [6465 4505 5936]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[5993 4277 5522]
 [6988 5142 6316]
 [6465 4505 5936]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[5993 4277 5522]
 [6988 5142 6316]
 [6465 4505 5936]], shape=(3, 3), dtype=int32)


In [ ]:
print(tf.matmul(x,y_reshape))
print(tf.tensordot(x,y_reshape,1))
print(x@y_reshape)
print("\n")
print(tf.matmul(x,y_transpose))
print(tf.tensordot(x,y_transpose,1))
print(x@y_transpose)

tf.Tensor(
[[2869 3450]
 [3614 3838]
 [3073 3584]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[2869 3450]
 [3614 3838]
 [3073 3584]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[2869 3450]
 [3614 3838]
 [3073 3584]], shape=(3, 2), dtype=int32)


tf.Tensor(
[[3662 3019]
 [4180 3370]
 [3832 3101]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[3662 3019]
 [4180 3370]
 [3832 3101]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[3662 3019]
 [4180 3370]
 [3832 3101]], shape=(3, 2), dtype=int32)


# Changing datatype of a tensor using:
* `tf.cast`
* `tf.dtypes`

In [218]:
x, y

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[37, 39, 11],
        [36, 42, 34],
        [33, 43, 21]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[48, 43, 19],
        [44, 32, 13]], dtype=int32)>)

In [222]:
tf.cast(x,dtype=tf.float32), tf.cast(y,tf.float16)

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[37., 39., 11.],
        [36., 42., 34.],
        [33., 43., 21.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float16, numpy=
 array([[48., 43., 19.],
        [44., 32., 13.]], dtype=float16)>)

# Finding the absolute value of a tensor using `tf.abs()`

In [225]:
tf.random.set_seed(42)
a = tf.random.normal([2,3,3])
a

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[ 0.3274685 , -0.8426258 ,  0.3194337 ],
        [-1.4075519 , -2.3880599 , -1.0392479 ],
        [-0.5573232 ,  0.539707  ,  1.6994323 ]],

       [[ 0.28893656, -1.5066116 , -0.26454744],
        [-0.59722406, -1.9171132 , -0.62044144],
        [ 0.8504023 , -0.40604794, -3.0258412 ]]], dtype=float32)>

In [227]:
a_abs = tf.abs(a)
a_abs

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[0.3274685 , 0.8426258 , 0.3194337 ],
        [1.4075519 , 2.3880599 , 1.0392479 ],
        [0.5573232 , 0.539707  , 1.6994323 ]],

       [[0.28893656, 1.5066116 , 0.26454744],
        [0.59722406, 1.9171132 , 0.62044144],
        [0.8504023 , 0.40604794, 3.0258412 ]]], dtype=float32)>

# Finding the max, min, mean, sum, variance and std_dev of a tensor using:
* `tf.reduce_max`
* `tf.reduce_min`
* `tf.reduce_mean`
* `tf.reduce_sum`
* `tf.math.reduce_variance`
* `tf.math.reduce_std`

In [231]:
tf.random.set_seed(42)
sample_tensor = tf.random.uniform([2,3,3],maxval=100,minval=0)
sample_tensor

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[66.45621  , 44.100677 , 35.28825  ],
        [46.448254 ,  3.3660412, 68.46724  ],
        [74.01174  , 87.24445  , 22.632635 ]],

       [[22.319687 , 31.038809 , 72.23358  ],
        [13.318718 , 54.80639  , 57.46088  ],
        [89.968346 ,  0.9463668, 52.12307  ]]], dtype=float32)>

In [240]:
print(tf.reduce_max(sample_tensor))
print(tf.reduce_min(sample_tensor))
print(tf.reduce_mean(sample_tensor))
print(tf.reduce_sum(sample_tensor))
print(tf.math.reduce_variance(sample_tensor))
print(tf.math.reduce_std(sample_tensor))

tf.Tensor(89.968346, shape=(), dtype=float32)
tf.Tensor(0.9463668, shape=(), dtype=float32)
tf.Tensor(46.790634, shape=(), dtype=float32)
tf.Tensor(842.23145, shape=(), dtype=float32)
tf.Tensor(701.6825, shape=(), dtype=float32)
tf.Tensor(26.48929, shape=(), dtype=float32)


# Finding the positional maximum and minimum of a tensor using:
* `tf.math.argmax`
* `tf.math.argmin`

In [270]:
tf.random.set_seed(42)
another_sample_tensor = tf.random.uniform([2,2,5],dtype=tf.int32,maxval = 100, minval=0,seed=10)
another_sample_tensor

<tf.Tensor: shape=(2, 2, 5), dtype=int32, numpy=
array([[[57, 68, 48, 90, 35],
        [89, 34, 36, 25, 41]],

       [[77, 43, 48, 94, 92],
        [42, 27, 36,  6, 69]]], dtype=int32)>

In [278]:
pmax = tf.math.argmax(another_sample_tensor,1)
pmax

<tf.Tensor: shape=(2, 5), dtype=int64, numpy=
array([[1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])>

In [280]:
pmin = tf.math.argmin(another_sample_tensor,1)
pmin

<tf.Tensor: shape=(2, 5), dtype=int64, numpy=
array([[0, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])>

# Removing 1-dimension of tensor shape using `tf.queeze`

In [284]:
tf.random.set_seed(42)
raw_tensor = tf.random.uniform([2,1,1,3,4],dtype=tf.int32,maxval=100,minval=0,seed=10)
raw_tensor

<tf.Tensor: shape=(2, 1, 1, 3, 4), dtype=int32, numpy=
array([[[[[57, 68, 48, 90],
          [35, 89, 34, 36],
          [25, 41, 77, 43]]]],



       [[[[48, 94, 92, 42],
          [27, 36,  6, 69],
          [62, 11, 96, 89]]]]], dtype=int32)>

In [285]:
tf.squeeze(raw_tensor)

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[57, 68, 48, 90],
        [35, 89, 34, 36],
        [25, 41, 77, 43]],

       [[48, 94, 92, 42],
        [27, 36,  6, 69],
        [62, 11, 96, 89]]], dtype=int32)>

# One-hot encoding in tensorflow using

In [300]:
tensor_one_hot = tf.one_hot([0,1,2],3,on_value=5,off_value=0,dtype=tf.int32)
tensor_one_hot

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[5, 0, 0],
       [0, 5, 0],
       [0, 0, 5]], dtype=int32)>