#In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorsFlow

More specifically, we're going to cover:
* Introduction to tensors
*Getting information from tensors
* Manipulating tensors
*Tensors & NumPy
* Using @t.f.functions (a way to speed up your regular Python functions)
*Using GPUs with TensorFlow or (TPUs)
*Exercises to try for yourself!

#Introducing to Tensors

In [ ]:
#Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.14.0


In [ ]:
#create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#check the dimension of our vector
vector.ndim

1

In [ ]:
#create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.,],
                              [8.,9.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#let's create a tensor
tensor = tf.constant([
                      [[1,2,3],[4,5,6],[19,20,21]],
                      [[7,8,9],[10,11,12],[22,23,24]],
                      [[13,14,15],[16,17,18],[25,26,27]]
                      ])
tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [19, 20, 21]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [22, 23, 24]],

       [[13, 14, 15],
        [16, 17, 18],
        [25, 26, 27]]], dtype=int32)>

In [ ]:
tensor.ndim

3

#What we've create so far

* Scalar: a single number
* Vector: a number with dimension (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of number
* Tensor: an n-deminsional array of number(where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

###creating tensors using `tf.variable`

In [ ]:
#create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#change 1 of the elements in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

##Creating random tensors

Random tensors are tensors of some abitrary size which contain random numbers.


In [ ]:
#create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

###Shuffle the order of elements in a tensor

In [ ]:
#Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn'y affect leaerning
not_shuffled = tf.constant([[10,7],
                           [3,4],
                           [2,5]])
#shuffled our  non_shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
@tf.function
def foo():
  a = tf.random.uniform([1], seed=1)
  b = tf.random.uniform([1], seed=1)
  return a, b
print(foo())  # prints '(A1, A1)'
print(foo())  # prints '(A2, A2)'

@tf.function
def bar():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b
print(bar())  # prints '(A1, A2)'
print(bar())  # prints '(A3, A4)'

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.15012848], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.15012848], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.11101711], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.11101711], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.8354591], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.15012848], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.46399975], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.11101711], dtype=float32)>)
