# What I know so far...

## Creating tensor using `tf.constant()`

### Importing library

In [ ]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

print("tensorflow version:",tf.__version__)
print("numpy version:",np.__version__)

tensorflow version: 2.14.0
numpy version: 1.23.5


### Creating scalar

In [ ]:
scalar = tf.constant([7],dtype=tf.float32)
print("scalar value:",scalar.numpy())
print("scalar shape:",scalar.shape)
print("scalar datatype:", scalar.dtype)
print("scalar size:",tf.size(scalar).numpy())
print("scalar dimension",scalar.ndim)

scalar value: [7.]
scalar shape: (1,)
scalar datatype: <dtype: 'float32'>
scalar size: 1
scalar dimension 1


### Creating vector

In [ ]:
vector = tf.constant([10,7],dtype=tf.float32)
print("vector value:",vector.numpy())
print("vector shape:",vector.shape)
print("vector datatype:",vector.dtype)
print("vector size:",tf.size(vector).numpy())
print("vector dimension:",vector.ndim)

vector value: [10.  7.]
vector shape: (2,)
vector datatype: <dtype: 'float32'>
vector size: 2
vector dimension: 1


### Creating matrix

In [ ]:
matrix = tf.constant([[10,7,4],[3,4,5],[5,3,5]],dtype=tf.float32)
print("matrix value:\n",matrix.numpy())
print("matrix shape:", matrix.shape)
print("matrix datatype:", matrix.dtype)
print("matrix size:",tf.size(matrix).numpy())
print("matrix dimension",vector.ndim)

matrix value:
 [[10.  7.  4.]
 [ 3.  4.  5.]
 [ 5.  3.  5.]]
matrix shape: (3, 3)
matrix datatype: <dtype: 'float32'>
matrix size: 9
matrix dimension 1


### Creating tensor

In [ ]:
tensor = tf.constant([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]],dtype=tf.float32)
print("tensor value:\n",tensor.numpy())
print("tensor shape:",tensor.shape)
print("tensor datatype:",tensor.dtype)
print("tensor size:",tf.size(tensor).numpy())
print("tensor dimension:",tensor.ndim)

tensor value:
 [[[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]]

 [[10. 11. 12.]
  [13. 14. 15.]
  [16. 17. 18.]]]
tensor shape: (2, 3, 3)
tensor datatype: <dtype: 'float32'>
tensor size: 18
tensor dimension: 3


## Creating tensor using `tf.Variable()`

In [ ]:
var = tf.Variable([[1,2,3],[4,5,6]],dtype=tf.float32)
var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [ ]:
var.assign([[4,5,6],[1,2,3]])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[4., 5., 6.],
       [1., 2., 3.]], dtype=float32)>

## Creating tensor using `tf.random.uniform()`

In [ ]:
uniform_tensor_x = tf.random.uniform([2,2],dtype=tf.float32,maxval=5,minval=0,seed=1)
uniform_tensor_y = tf.random.uniform([2,3,3],minval=0,maxval=10,dtype=tf.int32,seed=1)
uniform_tensor_x, uniform_tensor_y

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[4.955765  , 2.3023863 ],
        [0.26528955, 3.5248184 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
 array([[[2, 1, 0],
         [9, 7, 8],
         [9, 6, 2]],
 
        [[1, 1, 3],
         [6, 9, 2],
         [3, 8, 0]]], dtype=int32)>)

## Creating tensor using `tf.random.normal()`

In [ ]:
normal_tensor_x = tf.random.normal([2,2],seed=1)
normal_tensor_y = tf.random.normal([2,3,3],seed=1)
normal_tensor_x, normal_tensor_y

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-1.383913  , -0.76343   ],
        [-0.07620621,  2.9495769 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
 array([[[-0.4875954 ,  0.39139766, -0.16212492],
         [ 1.4603639 ,  1.0836557 ,  0.5992614 ],
         [ 0.6349026 , -1.2749499 ,  0.09173867]],
 
        [[-1.7330894 , -0.7865556 , -0.31195286],
         [-1.8357738 , -0.49902946, -0.19484793],
         [ 0.12462526,  1.0039567 , -0.23780617]]], dtype=float32)>)

## Creating tensor using:
 1. `tf.random.set_seed()`
 2. `tf.random.uniform()`
 3. `tf.random.normal()`

In [ ]:
tf.random.set_seed(42)
another_tensor_x = tf.random.uniform([2,2,3],dtype=tf.int32,minval=0,maxval=5,seed=1)
another_tensor_y = tf.random.normal([2,2],seed=1)
another_tensor_x, another_tensor_y

(<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[4, 0, 0],
         [1, 4, 0]],
 
        [[2, 2, 0],
         [1, 1, 1]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-1.499947  , -1.2420495 ],
        [ 0.52283144, -0.35879248]], dtype=float32)>)

## Shifting tensors using:
  1. `tf.random.shuffle()`
  2. `tf.transpose()`
  3. `tf.reshape()`

In [ ]:
tf.random.set_seed(42)
x = tf.random.uniform([2,3],dtype=tf.int32,minval=0,maxval=5,seed=1)
y = tf.random.uniform([3,3],dtype=tf.int32,minval=0,maxval=10,seed=1)
x,y

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[4, 0, 0],
        [1, 4, 0]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[0, 7, 5],
        [6, 1, 9],
        [7, 2, 2]], dtype=int32)>)

In [ ]:
shuffled_x = tf.random.shuffle(x)
shuffled_y = tf.random.shuffle(y)
shuffled_x, shuffled_y

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 4, 0],
        [4, 0, 0]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[7, 2, 2],
        [0, 7, 5],
        [6, 1, 9]], dtype=int32)>)

In [ ]:
transpose_x = tf.transpose(x)
transpose_y = tf.transpose(y)
transpose_x, transpose_y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[4, 1],
        [0, 4],
        [0, 0]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[0, 6, 7],
        [7, 1, 2],
        [5, 9, 2]], dtype=int32)>)

In [ ]:
tf.reshape(x,[3,2])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 0],
       [0, 1],
       [4, 0]], dtype=int32)>

## Tensor manipulation using:
1. `tf.add` or `tf.math.add` or `+`
2. `tf.subtract` or `tf.math.subtract` or `-`
3. `tf.multiply` or `tf.math.multiply` or `*`
4. `tf.divide` or `tf.math.divide` or `/`
5. `tf.matmul`
6. `tf.tensordot`
7. `@`

In [ ]:
tf.random.set_seed(42)
x = tf.random.uniform([3,3],dtype=tf.int32,maxval=50,minval=0,seed=1)
y = tf.random.uniform([2,3],dtype=tf.int32,maxval=100,minval=0,seed=1)
x, y

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 9, 45,  0],
        [36, 19, 30],
        [42, 32, 25]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[12, 43, 17],
        [41, 87, 85]], dtype=int32)>)

In [ ]:
print(tf.add(x,10))
print(tf.math.add(x,10))
print(x+10)

tf.Tensor(
[[19 55 10]
 [46 29 40]
 [52 42 35]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[19 55 10]
 [46 29 40]
 [52 42 35]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[19 55 10]
 [46 29 40]
 [52 42 35]], shape=(3, 3), dtype=int32)


In [ ]:
print(tf.subtract(x,10))
print(tf.math.subtract(x,10))
print(x-10)

tf.Tensor(
[[ -1  35 -10]
 [ 26   9  20]
 [ 32  22  15]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ -1  35 -10]
 [ 26   9  20]
 [ 32  22  15]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ -1  35 -10]
 [ 26   9  20]
 [ 32  22  15]], shape=(3, 3), dtype=int32)


In [ ]:
print(tf.multiply(x,10))
print(tf.math.multiply(x,10))
print(x*10)

tf.Tensor(
[[ 90 450   0]
 [360 190 300]
 [420 320 250]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 90 450   0]
 [360 190 300]
 [420 320 250]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 90 450   0]
 [360 190 300]
 [420 320 250]], shape=(3, 3), dtype=int32)


In [ ]:
print(tf.divide(x,10))
print(tf.math.divide(x,10))
print(x/10)

tf.Tensor(
[[0.9 4.5 0. ]
 [3.6 1.9 3. ]
 [4.2 3.2 2.5]], shape=(3, 3), dtype=float64)
tf.Tensor(
[[0.9 4.5 0. ]
 [3.6 1.9 3. ]
 [4.2 3.2 2.5]], shape=(3, 3), dtype=float64)
tf.Tensor(
[[0.9 4.5 0. ]
 [3.6 1.9 3. ]
 [4.2 3.2 2.5]], shape=(3, 3), dtype=float64)


In [ ]:
print(tf.matmul(x,tf.transpose(y)))
print(tf.tensordot(x,tf.transpose(y),1))

tf.Tensor(
[[2043 4284]
 [1759 5679]
 [2305 6631]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[2043 4284]
 [1759 5679]
 [2305 6631]], shape=(3, 2), dtype=int32)


## Getting the tensor's:
1. minimum using `tf.reduce_min`
2. maximum using `tf.reduce_max`
3. mean using `tf.reduce.mean`
4. sum using `tf.reduce_sum`
5. variance using `tf.math.reduce_variance`
6. std_dev using `tf.math.reduce_std`

In [ ]:
tf.random.set_seed(42)
x = tf.random.uniform([4,4],dtype=tf.int32,maxval=100,minval=50,seed=1)
x

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[59, 95, 50, 86],
       [69, 80, 92, 82],
       [75, 61, 66, 86],
       [97, 53, 54, 75]], dtype=int32)>

In [ ]:
print("minimum value of x is:",tf.reduce_min(x))
print("Maximum value of x is:",tf.reduce_max(x))
print("mean value of x is:",tf.reduce_mean(x))
print("sum of x is:", tf.reduce_sum(x))
print("variance of x is:",tf.math.reduce_variance(tf.cast(x,tf.float32)))
print("std dev of x is:",tf.math.reduce_std(tf.cast(x,tf.float32)))

minimum value of x is: tf.Tensor(50, shape=(), dtype=int32)
Maximum value of x is: tf.Tensor(97, shape=(), dtype=int32)
mean value of x is: tf.Tensor(73, shape=(), dtype=int32)
sum of x is: tf.Tensor(1180, shape=(), dtype=int32)
variance of x is: tf.Tensor(223.9375, shape=(), dtype=float32)
std dev of x is: tf.Tensor(14.964541, shape=(), dtype=float32)


## Creating tensors using numpy

In [ ]:
x = np.arange(1,100,2)
x = tf.constant(x)
x

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])>

In [ ]:
x = tf.range(0,75)
reshape = tf.reshape(x,[3,5,5])
x.shape, reshape

(TensorShape([75]),
 <tf.Tensor: shape=(3, 5, 5), dtype=int32, numpy=
 array([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24]],
 
        [[25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39],
         [40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49]],
 
        [[50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59],
         [60, 61, 62, 63, 64],
         [65, 66, 67, 68, 69],
         [70, 71, 72, 73, 74]]], dtype=int32)>)

In [ ]:
tf.range(1,10,2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

## Creating tensors using `tf.one_hot()`

In [ ]:
x = tf.one_hot([0,1,2,3,4],5,on_value=5,off_value=0,dtype=tf.int32)
x

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[5, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 5]], dtype=int32)>

## Creating tensors using `tf.ones()` and `tf.zeros()`

In [ ]:
ones = tf.ones([3,4])
zeros = tf.zeros([4,5])

zeros, ones

(<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32)>)